name: Deploy Release Build

# Trigger on release
on:
  release:
    types:
      - released

jobs:
  build_deploy_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Enable multi-architecture support on build node
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Build + Push image (tag = git release tag)
        run: |
          docker buildx build \
            --build-arg GIT_COMMIT="${{github.sha}}" \
            --platform "linux/arm/v7,linux/arm64" \
            --tag "${{secrets.REGISTRY_USERNAME}}/nexus3:${GITHUB_REF#refs/tags/}" \
            --output "type=image,push=true" \
            --file ./Dockerfile .

      - name: Build + Push image ("latest")
        run: |
          docker buildx build \
            --build-arg GIT_COMMIT="${{github.sha}}" \
            --platform "linux/arm/v7,linux/arm64" \
            --tag "${{secrets.REGISTRY_USERNAME}}/nexus3:latest" \
            --output "type=image,push=true" \
            --file ./Dockerfile .
